### ISSUE TITLE
v1.0 TODO

### ISSUE THREAD

**Issue by palkan** [anycable/docs.anycable.io#25]
- [x] Rack middlewares
- [x] RPC and anycable-go default host changes
- [x] Add note about cable_meta_tag (https://github.com/anycable/anycable-rails/issues/115)
- [x] Docker versioning
- [x] anycable-go disconnector guide
- [ ] Generator GIF
- [ ] RPC proto changes:
  - [ ] Actual changes (diff?)
  - [x] Migration plan (anycable-go v1.0 compatibility with v0.6)
  - [ ] Version check
- [ ] Stimulus Reflex
  - [ ] Session persistence
  - [ ] Cache store problem https://github.com/anycable/anycable-rails/issues/127#issuecomment-642336573
- [ ] Upgrade "How to write a server"
- [ ] Heroku upgrades:
  - [x] Add note about RPC app mem size (you need 50MB per 1k connections + RPC size)
- [x] Dark theme 😎
- [x] Actualize blog posts links (remove "From Action to Any", add new post)
- [ ] **Update home page (anycable.io)**
- [ ] ...
